name: Build & Deploy XSMB Top-3

on:
  schedule:
    # 12:35 UTC ≈ 19:35 Asia/Ho_Chi_Minh
    - cron: "35 12 * * *"
  workflow_dispatch: {}   # cho phép bấm Run thủ công

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater (crawl + build)
        run: |
          python xsmb_auto_update.py
          # Lấy bản gọn làm homepage
          cp index_top3_pretty.html index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Auto-update $(date -u '+%Y-%m-%d %H:%M:%S') UTC" || echo "No changes"
          git push

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
